
-- hyprland.lua — MSI Summit E16 AI Studio (arch-msi)
--
-- Nació de la plantilla autogenerada de Hyprland (sigue en
-- /usr/share/hypr/hyprland.lua), pero de eso ya no queda gran cosa: este
-- archivo se versiona en el repo desde el 2026-07-22 y su historia completa
-- está en Git. La cabecera de "AUTOGENERATED — EDIT ACCORDING TO THE WIKI"
-- se retiró el 2026-08-27 (tarea 2.5) por describir algo que dejó de ser
-- verdad hace meses.
--
-- Referencia: https://wiki.hypr.land/Configuring/Start/
-- No están puestas todas las opciones disponibles; para la lista completa,
-- la wiki.

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "eDP-1",
    mode     = "2560x1600@165.04",
    position = "0x0",
    scale    = "1.6",
})

-- Monitor externo por HDMI (LG UltraGear, 2560x1440@143.93). El puerto cuelga de
-- la dGPU NVIDIA: ver docs/PROJECT_CONTEXT.md §6 y el coste que tiene en RTD3.
--
-- `position = "auto-center-left"` lo coloca A LA IZQUIERDA del portátil, que es
-- donde está físicamente, y alinea los dos por el CENTRO vertical. Antes lo
-- recogía la regla genérica de abajo con `position = "auto"`, que encadena los
-- monitores hacia la DERECHA: el puntero salía por el borde equivocado.
--
-- El `-center-` es la segunda mitad del arreglo (2026-09-07). Con `auto-left` a
-- secas la Y queda clavada en 0, o sea alineados por el borde SUPERIOR, y como
-- el externo es mucho más alto en píxeles lógicos (1440 frente a 1000) el ratón
-- no cruzaba a la misma altura. Centrados, sí.
--
-- Todo relativo A PROPÓSITO: la regla es del PUERTO, no de este LG. Escribir
-- `position = "-2560x-220"` da hoy el mismo resultado exacto —comprobado— pero
-- ata la regla a un externo de 2560x1440. Con `auto-center-left` y
-- `mode = "preferred"` el cálculo lo rehace Hyprland con cualquier monitor.
--
-- Las cuatro direcciones válidas están en el propio binario:
--   auto · auto-{up,down,left,right} · auto-center-{up,down,left,right}
--
-- ⚠️ Para calibrar esto NO vale `hyprctl keyword`: con config Lua responde
-- "keyword can't work with non-legacy parsers". Se prueba en vivo con
--   hyprctl eval 'hl.monitor({ output = "HDMI-A-1", mode = "preferred", ... })'
-- y se deshace con `hyprctl reload`.
hl.monitor({
    output   = "HDMI-A-1",
    mode     = "preferred",
    position = "auto-center-left",
    scale    = 1,
})

-- Cualquier otra salida (USB-C/DP, proyectores): encadenada a la derecha.
hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = 1,
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "dolphin"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
--
-- OJO con los ejemplos de la plantilla, que se retiraron el 2026-08-27: sugerían
-- lanzar aquí `waybar & hyprpaper & firefox`, y eso NO describe este equipo.
-- El arranque real de cada pieza:
--   · hyprpaper → aquí abajo, con hl.on("hyprland.start", ...) — ver el porqué.
--   · waybar    → `waybar.service` (systemd de usuario), NO desde este archivo.
--   · dunst     → activación D-Bus; ni servicio habilitado ni exec aquí.

-- hyprpaper se lanza AQUÍ y no por `hyprpaper.service` (deshabilitado el
-- 2026-08-27). Es un cambio de arranque, no de fondo: el fondo sigue siendo el
-- de `hyprpaper.conf` (tarea 2.4), solo que aparece antes.
--
-- MEDIDO en el arranque del 2026-08-27, en tiempo monotónico desde el boot:
--     23.185  Hyprland arranca (wayland-wm@hyprland.desktop.service)
--     25.084  Hyprland avisa "listo" a systemd  (uwsm finalize)  +1,90 s
--     25.537  graphical-session.target activo                    +0,45 s
--     25.598  systemd lanza hyprpaper                            +0,06 s
--     25.683  hyprpaper ya ve la salida eDP-1                    +0,09 s
--
-- Los 0,5 s entre "listo" y el lanzamiento eran puro coste de systemd, y NO se
-- podían recortar por la vía de la unidad: hyprpaper.service lleva
-- `ConditionEnvironment=WAYLAND_DISPLAY`, y esa variable solo llega al entorno
-- de systemd cuando uwsm hace `finalize`, o sea al final de la inicialización
-- del compositor. Con systemd de por medio, ese instante es el suelo.
--
-- `hyprland.start` se dispara antes de ese aviso, así que lanzar hyprpaper aquí
-- se salta el suelo entero. Es también lo que hace la plantilla oficial.
--
-- CONTRAPARTIDA, que conviene tener presente: se pierde el `Restart=on-failure`
-- de la unidad. Si hyprpaper se cae a mitad de sesión, ya no vuelve solo; hay
-- que relanzarlo a mano. Para volver al arranque por systemd basta con comentar
-- este bloque y `systemctl --user enable --now hyprpaper.service`.
hl.on("hyprland.start", function ()
    hl.exec_cmd("hyprpaper")

    -- REGENERA EL TEMA con el fondo que hyprpaper acabe de elegir. Sin esto, el
    -- escritorio arrancaría con la paleta del fondo ANTERIOR: hyprpaper sortea
    -- una imagen distinta en cada arranque (order = random) y los artefactos
    -- del tema se quedan como estaban.
    --
    -- No hace falta esperar a hyprpaper aquí: `theme-apply` le pregunta por el
    -- fondo con `hyprctl hyprpaper listactive` reintentando durante 5 s, y si no
    -- contesta cae en la semilla de reserva en vez de quedarse colgado.
    --
    -- Se invoca POR NOMBRE, no por ruta: el paquete Stow `bin` lo enlaza en
    -- ~/.local/bin, que está en el PATH de la sesión (verificado en el entorno
    -- del propio Hyprland). Así esto no depende de dónde esté clonado el repo.
    hl.exec_cmd("theme-apply")

    -- CONECTA PROTONVPN al servidor más rápido. Réplica del comportamiento que
    -- el cliente de Windows trae de serie y que el de Linux NO tiene: no existe
    -- ningún ajuste de auto-conexión en `settings.json` ni en
    -- `protonvpn config set` (comprobado el 2026-09-06), y la conexión que crea
    -- el cliente vive en /run/NetworkManager/, o sea en tmpfs, así que no
    -- sobrevive al reinicio y NM no tiene nada que autoconectar.
    --
    -- NO conecta a ciegas: el script espera a que NetworkManager declare
    -- conectividad `full`, y si detecta un PORTAL CAUTIVO se aparta y avisa por
    -- notificación. Conectar antes de pasar el portal dejaría la sesión sin red
    -- y sin poder autenticarse. Detalle completo en el propio script.
    --
    -- Igual que theme-apply, se invoca POR NOMBRE: lo enlaza el paquete Stow
    -- `bin` en ~/.local/bin, que está en el PATH de la sesión.
    hl.exec_cmd("vpn-autoconnect")

    -- BAJA EL PANEL A 60 Hz con batería en el perfil power-saver, y lo devuelve
    -- a 165 Hz en cuanto se enchufa o se cambia de perfil. El panel solo ofrece
    -- esos dos modos (`hyprctl monitors`: availableModes), y el de arriba —el
    -- que fija la regla de eDP-1 de este archivo— es el nativo de 165 Hz, que
    -- con batería se paga en autonomía.
    --
    -- El demonio se queda escuchando tres cosas: los uevents de power_supply
    -- (enchufar/desenchufar), la señal ActiveProfile de power-profiles-daemon
    -- (cambio de perfil) y el `configreloaded` del socket2 —porque un
    -- `hyprctl reload`, que es justo con lo que termina `theme-apply`, re-aplica
    -- la regla de arriba y devolvería el panel a 165 Hz sin avisar—.
    --
    -- Igual que los dos anteriores, POR NOMBRE: lo enlaza el paquete Stow `bin`.
    hl.exec_cmd("panel-hz")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Modo oscuro para las aplicaciones Qt (Dolphin, y cualquier otra Qt6).
--
-- Sin esto, Qt no se entera de nada: con el escritorio en oscuro y el portal
-- anunciando `prefer-dark`, una comprobación con QStyleHints devolvía
-- `ColorScheme.Unknown` y un fondo de ventana #efefef, o sea blanco.
--
-- `xdgdesktopportal` hace que Qt lea la MISMA preferencia
-- (`org.freedesktop.appearance color-scheme`) que ya siguen Firefox, Electron y
-- GTK4. Una sola fuente de verdad para todo el sistema; la fija `theme-apply`
-- desde `matugen.mode` de tokens.toml. El plugin viene en qt6-base, no hace
-- falta instalar nada.
--
-- ⚠️ TRAMPA: la otra opción, `gtk3`, PARECE funcionar y no funciona. También
-- devuelve `ColorScheme.Dark`, pero pinta el fondo en #faf9f8 (blanco), porque
-- en este sistema no hay ningún tema Adwaita-dark de GTK3 en /usr/share/themes.
-- Comprobado el 2026-09-13 mirando la paleta, no el nombre del esquema.
hl.env("QT_QPA_PLATFORMTHEME", "xdgdesktopportal")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- COLORES Y MÉTRICAS: no se definen aquí. Los genera matugen a partir del fondo
-- de pantalla en `theme.lua`, que es un ARTEFACTO —archivo real junto a estos
-- enlaces, fuera del repo y fuera de Stow—. La plantilla versionada está en
-- dotfiles/matugen/.config/matugen/templates/hyprland-theme.lua y los valores
-- salen de theme/tokens.toml.
--
-- `dofile` y no `require`: `require` busca por package.path, que no incluye
-- ~/.config/hypr, y al ser este archivo un ENLACE de Stow la resolución sería
-- imprevisible — es el mismo problema que tuvo el `source` de hyprlock, que
-- acabó buscando dentro del repositorio. La ruta se construye desde $HOME, así
-- que no queda /home/elok cableado.
--
-- ⚠️ SI FALTA EL ARCHIVO, Hyprland se queda SIN CONFIGURAR. Por eso hay
-- respaldo: si `dofile` falla (una restauración recién hecha, matugen aún sin
-- ejecutar), se usan los valores de reserva de abajo y la sesión arranca igual.
local ok, theme = pcall(dofile, os.getenv("HOME") .. "/.config/hypr/theme.lua")
if not ok or type(theme) ~= "table" then
    theme = {
        accent = "rgba(7aa2f7ff)", accent_alt = "rgba(3d59a1ff)",
        surface = "rgba(16181dff)", outline = "rgba(595959aa)",
        shadow = "rgba(000000ee)",
        border_size = 2, rounding = 10, gaps_in = 5, gaps_out = 20,
    }
end

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = theme.gaps_in,
        gaps_out = theme.gaps_out,

        border_size = theme.border_size,

        col = {
            -- Era el degradado cian→verde de la plantilla de fábrica, lo último
            -- del escritorio que seguía fuera de la paleta del proyecto.
            -- LOS DOS COLORES SALEN DEL FONDO DE PANTALLA. Era el degradado
            -- cian→verde de la plantilla de fábrica; después, acento→magenta de
            -- identidad; desde el 2026-08-27, dos tonos de la paleta extraída
            -- de la imagen (ver accent_alt_family en tokens.toml).
            active_border   = { colors = { theme.accent, theme.accent_alt }, angle = 45 },
            inactive_border = theme.outline,
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = theme.rounding,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = theme.shadow,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- Reparto fijo de escritorios entre pantallas (2026-09-07):
--   1–5   → eDP-1      (portátil, pantalla principal)
--   6–10  → HDMI-A-1   (monitor externo)
--
-- Sin estas reglas el escritorio se creaba en la pantalla que tuviera el foco,
-- así que el mismo número caía un rato en una y un rato en otra y Super+N no
-- era un destino fijo. Con el reparto, Super+1..5 va siempre al portátil y
-- Super+6..0 salta al externo: el atajo cambia de pantalla además de escritorio
-- y no hace falta un bind aparte para moverse entre monitores.
--
-- NO son `persistent`: si se desenchufa el HDMI, del 6 al 10 solo existen los
-- que tengan ventanas, que se recogen en el portátil hasta que vuelva. La
-- persistencia visual de los diez botones la pone Waybar, no Hyprland.
--
-- `default` marca en qué escritorio aterriza cada pantalla al aparecer.
for i = 1, 10 do
    hl.workspace_rule({
        workspace = tostring(i),
        monitor   = i <= 5 and "eDP-1" or "HDMI-A-1",
        default   = i == 1 or i == 6,
    })
end

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- El layout activo es `dwindle` (verificado: hyprctl getoption general:layout),
-- así que el bloque `scrolling` de la plantilla no hacía nada y se retiró el
-- 2026-08-27. Si algún día se prueba ese layout, la referencia está en
-- https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        -- 0 = sin fondo por defecto de Hyprland (mascota / logo aleatorios).
        -- Era lo que asomaba durante el primer segundo del arranque: Hyprland
        -- pinta su fondo nada más abrir el monitor, y hyprpaper.service tarda
        -- un instante más en crear su capa. Con esto, ese hueco se ve del color
        -- de `misc:background_color` (0x111111 por defecto) en vez del fondo
        -- ajeno. El fondo real lo sigue poniendo hyprpaper (tarea 2.4).
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,

        -- Color de ese hueco (por defecto 0xff111111, un gris muy oscuro).
        -- Negro puro porque es el color del que ya viene la pantalla al salir
        -- de SDDM: cuanto menos cambie, menos se nota el cambio.
        background_color = 0xff000000,
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        -- DOS distribuciones cargadas en todos los teclados, en este orden:
        -- índice 0 = es, índice 1 = us. El portátil tiene serigrafía española,
        -- así que arranca en la primera. El teclado USB externo invierte el
        -- orden más abajo, en su `hl.device`.
        --
        -- Las dos tienen que estar en la lista para que Super+Espacio pueda
        -- alternar: `switchxkblayout next` ROTA entre las ya cargadas, no
        -- carga distribuciones nuevas.
        kb_layout  = "es,us",

        -- Las variantes van POSICIONALMENTE emparejadas con `kb_layout`: la
        -- primera está vacía (es, sin variante) y la segunda es `intl`, o sea
        -- US International con teclas muertas. Así la distribución americana
        -- da tildes, ñ y ç, y es la misma tanto aquí como en el teclado
        -- externo — un solo comportamiento que recordar. El porqué de `intl`
        -- y no `altgr-intl`, en el `hl.device` de abajo.
        kb_variant = ",intl",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = true,
        },
    },
})

hl.gesture({
    fingers = 3,
	    direction = "horizontal",
    action = "workspace"
})

-- Config por dispositivo: ver
-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/
-- Aquí había un `hl.device` de ejemplo para "epic-mouse-v1", retirado el
-- 2026-08-27: no existe tal dispositivo. Los reales de este equipo son
-- `elan0305:00-04f3:31fd-mouse` y `elan0305:00-04f3:31fd-touchpad`
-- (`hyprctl devices`), así que ese bloque no se aplicaba a nada.

-- Teclado USB externo (SEMITEK USB-HID Gaming Keyboard, 1EA7:0907), de
-- distribución AMERICANA (2026-09-07). Orden invertido respecto al global:
-- índice 0 = us, índice 1 = es. Así cada teclado arranca en SU serigrafía.
--
-- Son DOS entradas porque el teclado expone dos endpoints HID y los dos emiten
-- teclas (`grep -A6 -i semitek /proc/bus/input/devices`: `input0` alfanumérico
-- e `input2`, que además hace de ratón; ambos con handler `kbd`). Poniéndolo
-- solo en el primero, parte de las teclas seguiría interpretándose en es.
--
-- El nombre es el de `hyprctl devices`, no el del USB: Hyprland lo pasa a
-- minúsculas y sustituye los espacios por guiones.
--
-- `us` va con variante `intl` (US International CON TECLAS MUERTAS), para poder
-- escribir tildes, ñ y ç desde la distribución americana. Emparejamiento
-- posicional otra vez, e invertido respecto al global porque aquí `us` va
-- primero: "intl," = us→intl, es→sin variante.
--
-- ⚠️ NO es `altgr-intl`, y es una decisión tomada PROBANDO LAS DOS el
-- 2026-09-07. La disyuntiva es qué se pone en el nivel base y qué en AltGr:
--
--   intl        ' " ` ~ ^ muertas en el base; tilde = ' + vocal
--   altgr-intl  ' " ` ~ ^ literales en el base; tilde = AltGr + ' + vocal
--
-- Gana `intl` porque los acentos se escriben mucho más a menudo que las
-- comillas, y porque **el nivel de AltGr de `intl` sigue dando el carácter
-- literal**: AltGr + ' = ', AltGr + Shift + ' = ", AltGr + ` = `,
-- AltGr + Shift + ` = ~, AltGr + Shift + 6 = ^. O sea que con `intl` no se
-- pierde nada, solo cambia qué cuesta una pulsación y qué cuesta dos. Con
-- `altgr-intl` sería al revés, y lo caro serían las tildes.
-- Ver /usr/share/X11/xkb/symbols/us; AltGr es el Alt DERECHO
-- (`include "level3(ralt_switch)"`).
for _, teclado in ipairs({
    "semitek-usb-hid-gaming-keyboard",
    "semitek-usb-hid-gaming-keyboard-1",
}) do
    hl.device({ name = teclado, kb_layout = "us,es", kb_variant = "intl," })
end

-- Lápiz y táctil de la pantalla (ELAN9024:00 04F3:4297) anclados al panel
-- interno (2026-09-12).
--
-- El digitalizador reporta coordenadas ABSOLUTAS sobre su propia superficie.
-- Sin `output`, Hyprland las estira sobre el ÁREA COMBINADA de todas las
-- salidas, no sobre el panel que estás tocando. Con el monitor externo puesto
-- esa área pasa a ser ~4160x1220 lógicos (`hyprctl monitors`: HDMI-A-1
-- 2560x1440 en -2560x-220 y eDP-1 2560x1600 a escala 1,6 = 1600x1000 en 0x0),
-- así que el trazo sale desplazado respecto a la punta del lápiz. Con un solo
-- monitor las dos áreas coinciden, y por eso sin HDMI calibra bien.
--
-- Son DOS entradas porque `hyprctl devices` los lista por separado: el lápiz
-- en `Tablets` (sufijo `-stylus`) y el dedo en `Touch` (sin sufijo).
for _, puntero in ipairs({
    "elan9024:00-04f3:4297-stylus", -- lápiz (sección Tablets)
    "elan9024:00-04f3:4297",        -- táctil (sección Touch)
}) do
    hl.device({ name = puntero, output = "eDP-1" })
end


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
-- Bloqueo manual. Vía dbus, NO `hyprlock` directo: así hypridle recibe el
-- evento y lanza su `lock_cmd` (ver hypridle.conf). Sin `locked = true`: con la
-- sesión ya bloqueada no debe hacer nada.
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("rofi -show drun"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Selector de símbolos que no están en el teclado (griegas, operadores, flechas
-- y sub/superíndices), buscables por nombre en castellano. Escribe el elegido
-- en la ventana enfocada si hay `wtype`; si no, lo deja en el portapapeles.
-- Ver scripts/simbolos.sh. G de "griego".
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("simbolos"))

-- Alterna es/us EN EL TECLADO QUE PULSA EL ATAJO, sin tocar el otro: el estado
-- de xkb es por dispositivo. Ver scripts/kb-layout.sh.
-- Se resuelve por CÓDIGO de tecla, no por símbolo (`resolve_binds_by_sym` está
-- en su valor por defecto), así que el atajo sigue en la misma tecla física en
-- ambas distribuciones.
hl.bind(mainMod .. " + space", hl.dsp.exec_cmd("kb-layout"))

-- Notificaciones (dunst, tarea 2.2).
-- `history-pop` recupera la última notificación cerrada; con
-- `sticky_history = yes` en dunstrc se queda fija hasta cerrarla, en vez de
-- volver a expirar en 5-10 s. El historial guarda 20 y VIVE EN MEMORIA: se
-- pierde entero si dunst se reinicia o se cierra la sesión.
-- Sin `locked = true` en ninguno de los dos: con la sesión bloqueada dunst
-- está pausado a propósito (ver on_lock_cmd en hypridle.conf), así que sacar
-- notificaciones del historial sobre hyprlock sería justo lo contrario.
hl.bind(mainMod .. " + N",           hl.dsp.exec_cmd("dunstctl history-pop"))
hl.bind(mainMod .. " + SHIFT + N",   hl.dsp.exec_cmd("dunstctl close-all"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Alterna la salida de audio de TODO el sistema entre la interfaz USB (SSL 2+)
-- y los altavoces del portátil, sin desenchufar la interfaz. El script mueve
-- también los flujos que ya estaban sonando, cosa que `pactl set-default-sink`
-- por sí solo no hace. Ver scripts/audio-salida.sh.
hl.bind(mainMod .. " + Z", hl.dsp.exec_cmd("audio-salida"))

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
-- El "-p playerctld,%any" importa, y las dos partes hacen falta:
--   playerctld -> el player que usaste por ultima vez. Sin esto, playerctl
--                 actua sobre el primero que enumera y ese orden NO es estable:
--                 con Firefox y Spotify abiertos, el play/pause se lo llevaba
--                 Firefox unas veces si y otras no.
--   %any       -> cualquier otro player, como reserva. Hace falta porque no
--                 todos saben hacer todo: una pagina de YouTube en Firefox
--                 declara CanGoNext = false, asi que el boton de cancion
--                 siguiente cae solo en el player que si pueda (Spotify).
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl -p playerctld,%any next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl -p playerctld,%any play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl -p playerctld,%any play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl -p playerctld,%any previous"),   { locked = true })

-- Screenshots (grim + slurp + swappy)
hl.bind("Print",               hl.dsp.exec_cmd([[grim -g "$(slurp)" - | wl-copy]]))
hl.bind("CTRL + Print",        hl.dsp.exec_cmd([[grim - | wl-copy]]))
hl.bind("SHIFT + Print",       hl.dsp.exec_cmd([[mkdir -p "$HOME/Screenshots" && grim -g "$(slurp)" "$HOME/Screenshots/$(date +%Y%m%d-%H%M%S).png"]]))
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd([[grim -g "$(slurp)" - | swappy -f -]]))


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})
