
-- hyprland.lua — MSI Summit E16 AI Studio (arch-msi)
--
-- Nació de la plantilla autogenerada de Hyprland (sigue en
-- /usr/share/hypr/hyprland.lua), pero de eso ya no queda gran cosa: este
-- archivo se versiona en el repo desde el 2026-07-22 y su historia completa
-- está en Git. La cabecera de "AUTOGENERATED — EDIT ACCORDING TO THE WIKI"
-- se retiró el 2026-08-27 (tarea 2.5) por describir algo que dejó de ser
-- verdad hace meses.
--
-- Referencia: https://wiki.hypr.land/Configuring/Start/
-- No están puestas todas las opciones disponibles; para la lista completa,
-- la wiki.

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "eDP-1",
    mode     = "2560x1600@165.04",
    position = "0x0",
    scale    = "1.6",
})

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = 1,
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "dolphin"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
--
-- OJO con los ejemplos de la plantilla, que se retiraron el 2026-08-27: sugerían
-- lanzar aquí `waybar & hyprpaper & firefox`, y eso NO describe este equipo.
-- El arranque real de cada pieza:
--   · hyprpaper → aquí abajo, con hl.on("hyprland.start", ...) — ver el porqué.
--   · waybar    → `waybar.service` (systemd de usuario), NO desde este archivo.
--   · dunst     → activación D-Bus; ni servicio habilitado ni exec aquí.

-- hyprpaper se lanza AQUÍ y no por `hyprpaper.service` (deshabilitado el
-- 2026-08-27). Es un cambio de arranque, no de fondo: el fondo sigue siendo el
-- de `hyprpaper.conf` (tarea 2.4), solo que aparece antes.
--
-- MEDIDO en el arranque del 2026-08-27, en tiempo monotónico desde el boot:
--     23.185  Hyprland arranca (wayland-wm@hyprland.desktop.service)
--     25.084  Hyprland avisa "listo" a systemd  (uwsm finalize)  +1,90 s
--     25.537  graphical-session.target activo                    +0,45 s
--     25.598  systemd lanza hyprpaper                            +0,06 s
--     25.683  hyprpaper ya ve la salida eDP-1                    +0,09 s
--
-- Los 0,5 s entre "listo" y el lanzamiento eran puro coste de systemd, y NO se
-- podían recortar por la vía de la unidad: hyprpaper.service lleva
-- `ConditionEnvironment=WAYLAND_DISPLAY`, y esa variable solo llega al entorno
-- de systemd cuando uwsm hace `finalize`, o sea al final de la inicialización
-- del compositor. Con systemd de por medio, ese instante es el suelo.
--
-- `hyprland.start` se dispara antes de ese aviso, así que lanzar hyprpaper aquí
-- se salta el suelo entero. Es también lo que hace la plantilla oficial.
--
-- CONTRAPARTIDA, que conviene tener presente: se pierde el `Restart=on-failure`
-- de la unidad. Si hyprpaper se cae a mitad de sesión, ya no vuelve solo; hay
-- que relanzarlo a mano. Para volver al arranque por systemd basta con comentar
-- este bloque y `systemctl --user enable --now hyprpaper.service`.
hl.on("hyprland.start", function ()
    hl.exec_cmd("hyprpaper")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- El layout activo es `dwindle` (verificado: hyprctl getoption general:layout),
-- así que el bloque `scrolling` de la plantilla no hacía nada y se retiró el
-- 2026-08-27. Si algún día se prueba ese layout, la referencia está en
-- https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        -- 0 = sin fondo por defecto de Hyprland (mascota / logo aleatorios).
        -- Era lo que asomaba durante el primer segundo del arranque: Hyprland
        -- pinta su fondo nada más abrir el monitor, y hyprpaper.service tarda
        -- un instante más en crear su capa. Con esto, ese hueco se ve del color
        -- de `misc:background_color` (0x111111 por defecto) en vez del fondo
        -- ajeno. El fondo real lo sigue poniendo hyprpaper (tarea 2.4).
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,

        -- Color de ese hueco (por defecto 0xff111111, un gris muy oscuro).
        -- Negro puro porque es el color del que ya viene la pantalla al salir
        -- de SDDM: cuanto menos cambie, menos se nota el cambio.
        background_color = 0xff000000,
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "es",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = true,
        },
    },
})

hl.gesture({
    fingers = 3,
	    direction = "horizontal",
    action = "workspace"
})

-- Config por dispositivo: ver
-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/
-- Aquí había un `hl.device` de ejemplo para "epic-mouse-v1", retirado el
-- 2026-08-27: no existe tal dispositivo. Los reales de este equipo son
-- `elan0305:00-04f3:31fd-mouse` y `elan0305:00-04f3:31fd-touchpad`
-- (`hyprctl devices`), así que ese bloque no se aplicaba a nada.


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
-- Bloqueo manual. Vía dbus, NO `hyprlock` directo: así hypridle recibe el
-- evento y lanza su `lock_cmd` (ver hypridle.conf). Sin `locked = true`: con la
-- sesión ya bloqueada no debe hacer nada.
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("rofi -show drun"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Notificaciones (dunst, tarea 2.2).
-- `history-pop` recupera la última notificación cerrada; con
-- `sticky_history = yes` en dunstrc se queda fija hasta cerrarla, en vez de
-- volver a expirar en 5-10 s. El historial guarda 20 y VIVE EN MEMORIA: se
-- pierde entero si dunst se reinicia o se cierra la sesión.
-- Sin `locked = true` en ninguno de los dos: con la sesión bloqueada dunst
-- está pausado a propósito (ver on_lock_cmd en hypridle.conf), así que sacar
-- notificaciones del historial sobre hyprlock sería justo lo contrario.
hl.bind(mainMod .. " + N",           hl.dsp.exec_cmd("dunstctl history-pop"))
hl.bind(mainMod .. " + SHIFT + N",   hl.dsp.exec_cmd("dunstctl close-all"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

-- Screenshots (grim + slurp + swappy)
hl.bind("Print",               hl.dsp.exec_cmd([[grim -g "$(slurp)" - | wl-copy]]))
hl.bind("CTRL + Print",        hl.dsp.exec_cmd([[grim - | wl-copy]]))
hl.bind("SHIFT + Print",       hl.dsp.exec_cmd([[mkdir -p "$HOME/Screenshots" && grim -g "$(slurp)" "$HOME/Screenshots/$(date +%Y%m%d-%H%M%S).png"]]))
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd([[grim -g "$(slurp)" - | swappy -f -]]))


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})
